name: Second workflow excercise
on:
  issues: 
    types: [opened]
jobs: 
  output-event-details:
    runs-on: ubuntu-latest
    steps:
      - name: Print object
        run: echo "${{toJson(github)}}"
